#!/usr/bin/env python
 
import sys, time
from daemon import Daemon

import urllib
import urllib2
import RPi.GPIO as GPIO
import time
import logging
from time import gmtime, strftime

bot_id = "433972911:AAGxjeRPDHo7CfJgOQrfLrdoj_GwgKN4cMo"
# bot_id = "250864950:AAHD2HHsoXEvVlY5tk1I9kVFtlz4rOTMn9Y"
chat_id = -211695310
logging.basicConfig(filename='/var/log/lavadora.log',level=logging.DEBUG)

def sendMessage(message):
        result = urllib2.urlopen("https://api.telegram.org/bot" + bot_id + "/sendMessage", urllib.urlencode({ "chat_id": -211695310, "text": message })).read()
        print(result)

def log(message):
        logging.info(strftime("%Y-%m-%d %H:%M:%S", gmtime())+' '+message)


class MyDaemon(Daemon):
        def run(self):
	        mode=GPIO.getmode()
		GPIO.cleanup()
		GPIO.setmode(GPIO.BCM)
		GPIO.setup(4, GPIO.IN)
		GPIO.setup(17, GPIO.IN)

		sendMessage('script iniciado')
		log('script iniciado')

		last_tilt = 0
		last_ball = 0

                while True:

		        current_tilt = GPIO.input(4)
			current_ball = GPIO.input(17)

			if (current_tilt != last_tilt):
				last_tilt = current_tilt
			        mensagem = 'tilt'
				print(mensagem)
				sendMessage(mensagem)
				log(mensagem)

			if (current_ball != last_ball):
				last_ball = current_ball
				mensagem = 'ball'
				print(mensagem)
				sendMessage(mensagem)
				log(mensagem)

			time.sleep(0.1)
 
if __name__ == "__main__":
        daemon = MyDaemon('/tmp/daemon-example.pid')
        if len(sys.argv) == 2:
                if 'start' == sys.argv[1]:
                        daemon.start()
                elif 'stop' == sys.argv[1]:
                        daemon.stop()
                elif 'restart' == sys.argv[1]:
                        daemon.restart()
                else:
                        print "Unknown command"
                        sys.exit(2)
                sys.exit(0)
        else:
                print "usage: %s start|stop|restart" % sys.argv[0]
                sys.exit(2)
